# --- mm model ---
mm_model_dim: 512

# --- Dataset / Data Split ---
train_csv: "./data/train.csv"
val_csv: "./data/val.csv"
test_csv: "./data/test.csv"
image_dir: "./images/" # 所有清理好的圖片統一放此資料夾

# --- Training ---
use_log: True
lr: 0.001
batch_size: 32
epochs: 20
weight_decay: 0.0002
loss_type: "mae"  # 可選："mae"、"mse"、"huber"

# --- meta ---
meta_input_dim: 51        # number of meta features
meta_hidden_dims: [512,360] #  hidden layers
meta_embedding_dim: 128    # final embedding size
meta_dropout: 0.1            # % of dropout
meta_encoder_ckpt: "meta/meta_encoder.pth"
meta_pretrain: False # pretrained or not

