# --- mm model ---
mm_model_dim: 512
mm_model_num_layers: 3

# --- Dataset / Data Split ---

# 資料集設定說明：
# - train:        完整資料，未刪除 outliers
# - train_out:    已刪除 outliers 的資料
# - train_robust: 使用 stratify 且刪除 outliers 的資料

train_csv: "./data/train_robust.csv"
val_csv: "./data/val_robust.csv"
test_csv: "./data/test_robust.csv"
image_dir: "./images/" # 所有清理好的圖片統一放此資料夾


# --- Training ---
use_log: True
# lr: 0.03
# batch_size: 30
# epochs: 5
# weight_decay: 0.01
# loss_type: "mse"  # 可選："mae"、"mse"、"huber"
# huber_beta: 5.0  # huber loss 的 beta 值
loss_type: 'quantile'
lr: 0.0005           # Much lower LR
epochs: 100        # More epochs with early stopping
individual_epochs: 40 # No k-fold CV, so individual epochs
batch_size: 40    # Smaller batches
weight_decay: 0.02 # Strong regularization
n_splits: 5        # 5-fold CV
patience: 15       # Patient early stopping
huber_beta: 10.0
quantile_q: 0.7
asymmetric_alpha: 1.5



# --- meta ---
meta_input_dim: 51        # number of meta features
meta_hidden_dims: [256,512,256] #  hidden layers
meta_embedding_dim: 128    # final embedding size
meta_dropout: 0.05          # % of dropout
meta_encoder_ckpt: "meta/meta_encoder.pth"
meta_pretrain: False # pretrained or not

